### ISSUE TITLE
TypeError: Cannot read property 'height' of undefined

### ISSUE THREAD

**Issue by vecchiotom** [JamesTheHacker/meme-maker#1]
TypeError: Cannot read property 'height' of undefined
    at gm.<anonymous> (C:\Users\admin\node_modules\meme-maker\meme-maker.js:46:43)
    at emitMany (events.js:127:13)
    at gm.emit (events.js:204:7)
    at gm.<anonymous> (C:\Users\admin\node_modules\gm\lib\getters.js:70:16)
    at cb (C:\Users\admin\node_modules\gm\lib\command.js:322:16)
    at ChildProcess.<anonymous> (C:\Users\admin\node_modules\gm\lib\command.js:232:9)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\admin\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
HOW DO I FIX THIS?

**Comment by JamesTheHacker** [comment]
Could you paste the code that's causing the error?
